# -*- coding: utf-8 -*-
{   'author': 'dnaj25',
    'category': 'Accounting',
    'currency': 'EUR',
    'data': [   'data/sequence.xml',
                'data/recurring_cron.xml',
                'security/ir.model.access.csv',
                'views/recurring_template_view.xml',
                'views/recurring_payment_view.xml'],
    'depends': ['account'],
    'description': 'Odoo 19 Recurring Payment, Recurring Payment In Odoo, Odoo 19 Accounting',
    'images': ['static/description/banner.png'],
    'license': 'LGPL-3',
    'name': 'Recurring Payments & Entries',
    'price': 29.0,
    'sequence': 11,
    'summary': 'Use recurring payments to handle periodically repeated payments',
    'version': '1.0.0',
    'website': 'https://github.com/dnaj25/odoo-addons'}