# -*- coding: utf-8 -*-
{   'author': 'dnaj25',
    'category': 'Invoicing Management',
    'company': 'Odoo Mates',
    'currency': 'EUR',
    'data': [   'security/ir.model.access.csv',
                'data/account_account_type.xml',
                'views/menu.xml',
                'views/ledger_menu.xml',
                'views/financial_report.xml',
                'views/settings.xml',
                'wizard/account_report_common_view.xml',
                'wizard/partner_ledger.xml',
                'wizard/general_ledger.xml',
                'wizard/trial_balance.xml',
                'wizard/balance_sheet.xml',
                'wizard/profit_and_loss.xml',
                'wizard/tax_report.xml',
                'wizard/aged_partner.xml',
                'wizard/journal_audit.xml',
                'report/report.xml',
                'report/report_partner_ledger.xml',
                'report/report_general_ledger.xml',
                'report/report_trial_balance.xml',
                'report/report_financial.xml',
                'report/report_tax.xml',
                'report/report_aged_partner.xml',
                'report/report_journal_audit.xml',
                'report/report_journal_entries.xml'],
    'depends': ['account'],
    'description': 'Accounting Reports For Odoo 19, Accounting Financial Reports, Odoo 19 Financial Reports',
    'images': ['static/description/banner.png'],
    'license': 'LGPL-3',
    'live_test_url': 'https://www.youtube.com/watch?v=yA4NLwOLZms',
    'maintainer': 'Odoo Mates',
    'name': 'Financial PDF Reports & Audits',
    'pre_init_hook': '_pre_init_clean_m2m_models',
    'price': 39.0,
    'sequence': '1',
    'summary': 'Accounting Reports For Odoo 19',
    'support': 'odoomates@gmail.com',
    'version': '1.0.2',
    'website': 'https://github.com/dnaj25/odoo-addons'}