# -*- coding: utf-8 -*-
{   'author': 'dnaj25',
    'category': 'Accounting',
    'currency': 'EUR',
    'data': [   'security/security.xml',
                'security/ir.model.access.csv',
                'data/mail_template_data.xml',
                'wizard/followup_print_view.xml',
                'wizard/followup_results_view.xml',
                'views/followup_view.xml',
                'views/account_move.xml',
                'views/partners.xml',
                'views/report_followup.xml',
                'views/reports.xml',
                'views/followup_partner_view.xml',
                'report/followup_report.xml'],
    'demo': ['demo/demo.xml'],
    'depends': ['account', 'mail'],
    'description': 'Customer FollowUp Management',
    'images': ['static/description/banner.png'],
    'license': 'LGPL-3',
    'name': 'Customer Follow-Up & Reminders',
    'price': 29.0,
    'summary': 'Customer FollowUp Management',
    'version': '1.0.2',
    'website': 'https://github.com/dnaj25/odoo-addons'}