# -*- coding: utf-8 -*-
{   'author': 'dnaj25',
    'category': 'Accounting',
    'currency': 'EUR',
    'data': [   'security/ir.model.access.csv',
                'security/security.xml',
                'views/account_analytic_account_views.xml',
                'views/account_budget_views.xml',
                'views/res_config_settings_views.xml'],
    'demo': ['data/account_budget_demo.xml'],
    'depends': ['account'],
    'description': 'Use budgets to compare actual with expected revenues and costs',
    'images': ['static/description/banner.png'],
    'license': 'LGPL-3',
    'name': 'Budget Management for Community',
    'price': 29.0,
    'sequence': 10,
    'summary': 'Odoo 19 Budget Management',
    'version': '1.0.1',
    'website': 'https://github.com/dnaj25/odoo-addons'}