{
    'name': 'Budget Management for Community',
    'category': 'Accounting',
    'version': '1.0.1',
    'description': """Use budgets to compare actual with expected revenues and costs""",
    'summary': 'Odoo 19 Budget Management',
    'sequence': 10,
    'depends': ['account'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/account_analytic_account_views.xml',
        'views/account_budget_views.xml',
        'views/res_config_settings_views.xml',
    ],
    'demo': ['data/account_budget_demo.xml'],
    'author': 'dnaj25',
    'website': 'https://github.com/dnaj25/odoo-addons',
    'price': 29.00,
    'currency': 'EUR',
    'images': ['static/description/icon.png'],
    'license': 'LGPL-3',
}
