# -*- coding: utf-8 -*-
{   'application': False,
    'assets': {'web.assets_frontend': ['switch_login_theme/static/src/scss/login_theme.scss']},
    'author': 'dnaj25',
    'auto_install': False,
    'category': 'Theme/Corporate',
    'currency': 'EUR',
    'data': ['views/login_templates.xml'],
    'depends': ['web'],
    'description': 'A premium, modern branded login screen for Odoo 19 - replace the default login with a beautiful dark-themed page.',
    'images': ['static/description/banner.png'],
    'installable': True,
    'license': 'LGPL-3',
    'name': 'Branded Login Theme',
    'price': 29.0,
    'summary': 'Premium branded login page theme for Odoo 19 Community',
    'version': '19.0.1.0.0',
    'website': 'https://github.com/dnaj25/odoo-addons'}