# -*- coding: utf-8 -*-
{   'application': True,
    'author': 'dnaj25',
    'category': 'Accounting',
    'currency': 'EUR',
    'data': [   'security/group.xml',
                'views/menu.xml',
                'views/settings.xml',
                'views/account_group.xml',
                'views/account_tag.xml',
                'views/res_partner.xml',
                'views/account_bank_statement.xml',
                'views/payment_method.xml',
                'views/reconciliation.xml',
                'views/account_journal.xml'],
    'depends': [   'community_pdf_reports',
                   'community_accounting_asset',
                   'community_accounting_budget',
                   'community_accounting_fiscal_year',
                   'community_accounting_recurring_payments',
                   'community_accounting_daily_reports',
                   'community_accounting_followup'],
    'description': 'Odoo 19 Financial Reports, Asset Management and Budget, Financial Reports, Recurring Payments, '
                   'Bank Statement Import, Customer Follow Up Management,Account Lock Date, Accounting Dashboard',
    'images': ['static/description/banner.png'],
    'license': 'LGPL-3',
    'live_test_url': 'https://www.youtube.com/c/OdooMates',
    'maintainer': 'Odoo Mates, Walnut Software Solutions',
    'name': 'Odoo 19 Accounting Community Kit',
    'price': 99.0,
    'sequence': '1',
    'summary': 'Accounting Reports, Asset Management and Budget, Recurring Payments, Lock Dates, Fiscal Year, '
               'Accounting Dashboard, Financial Reports, Customer Follow up Management, Bank Statement Import',
    'support': 'odoomates@gmail.com',
    'version': '1.0.3',
    'website': 'https://github.com/dnaj25/odoo-addons'}