# -*- coding: utf-8 -*-
{   'author': 'dnaj25',
    'category': 'Accounting',
    'currency': 'EUR',
    'data': [   'security/security.xml',
                'security/ir.model.access.csv',
                'wizard/change_lock_date.xml',
                'views/fiscal_year.xml',
                'views/settings.xml'],
    'depends': ['account'],
    'description': 'Odoo 19 Fiscal Year, Fiscal Year in Odoo 19',
    'images': ['static/description/banner.png'],
    'license': 'LGPL-3',
    'live_test_url': 'https://www.youtube.com/watch?v=Kj4hR7_uNs4',
    'maintainer': 'Odoo Mates',
    'name': 'Fiscal Years & Lock Dates',
    'price': 19.0,
    'sequence': '1',
    'summary': 'Odoo 19 Fiscal Year, Fiscal Year in Odoo 19, Lock Date in Odoo 19',
    'support': 'odoomates@gmail.com',
    'version': '1.0.1',
    'website': 'https://github.com/dnaj25/odoo-addons'}