{
    'name': 'Fiscal Years & Lock Dates',
    'version': '1.0.1',
    'category': 'Accounting',
    'summary': 'Odoo 19 Fiscal Year, Fiscal Year in Odoo 19, Lock Date in Odoo 19',
    'description': 'Odoo 19 Fiscal Year, Fiscal Year in Odoo 19',
    'live_test_url': 'https://www.youtube.com/watch?v=Kj4hR7_uNs4',
    'sequence': '1',
    'maintainer': 'Odoo Mates',
    'support': 'odoomates@gmail.com',
    'depends': ['account'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'wizard/change_lock_date.xml',
        'views/fiscal_year.xml',
        'views/settings.xml',
    ],
    'author': 'dnaj25',
    'website': 'https://github.com/dnaj25/odoo-addons',
    'price': 19.00,
    'currency': 'EUR',
    'images': ['static/description/icon.png'],
    'license': 'LGPL-3',
}
