# -*- coding: utf-8 -*-
{   'application': True,   'assets': {   'web._assets_primary_variables': {   '/web_responsive_pro/static/src/legacy/scss/form_variable.scss',
                                                       '/web_responsive_pro/static/src/legacy/scss/primary_variable.scss'},
                  'web.assets_backend': [   'web_responsive_pro/static/src/lib/fuse/fuse.basic.min.js',
                                            '/web_responsive_pro/static/src/legacy/scss/web_responsive_pro.scss',
                                            '/web_responsive_pro/static/src/legacy/scss/big_boxes.scss',
                                            '/web_responsive_pro/static/src/legacy/scss/list_sticky_header.scss',
                                            '/web_responsive_pro/static/src/legacy/js/web_responsive_pro.esm.js',
                                            '/web_responsive_pro/static/src/legacy/xml/form_buttons.xml',
                                            '/web_responsive_pro/static/src/legacy/xml/custom_favorite_item.xml',
                                            '/web_responsive_pro/static/src/components/apps_menu_tools.esm.js',
                                            '/web_responsive_pro/static/src/components/apps_menu/*',
                                            '/web_responsive_pro/static/src/components/apps_menu_item/*',
                                            '/web_responsive_pro/static/src/components/menu_canonical_searchbar/*',
                                            '/web_responsive_pro/static/src/components/menu_odoo_searchbar/*',
                                            '/web_responsive_pro/static/src/components/menu_fuse_searchbar/*',
                                            '/web_responsive_pro/static/src/components/menu_searchbar/*',
                                            '/web_responsive_pro/static/src/components/hotkey/*',
                                            '/web_responsive_pro/static/src/components/file_viewer/*',
                                            '/web_responsive_pro/static/src/components/chatter/*',
                                            '/web_responsive_pro/static/src/components/control_panel/*',
                                            '/web_responsive_pro/static/src/components/command_palette/*',
                                            '/web_responsive_pro/static/src/views/form/*',
                                            ('remove', 'web_responsive_pro/static/src/**/*.dark.scss')],
                  'web.assets_clickbot': ['/web_responsive_pro/static/src/clickbot/clickbot.esm.js'],
                  'web.assets_web_dark': ['web_responsive_pro/static/src/**/*.dark.scss'],
                  'web.qunit_suite_tests': [   '/web_responsive_pro/static/tests/apps_menu_tests.esm.js',
                                               '/web_responsive_pro/static/tests/apps_menu_search_tests.esm.js']},
    'author': 'dnaj25',
    'category': 'Website',
    'currency': 'EUR',
    'data': ['views/res_users_views.xml'],
    'depends': ['web', 'web_tour', 'mail'],
    'development_status': 'Production/Stable',
    'excludes': ['web_enterprise'],
    'images': ['static/description/banner.png'],
    'installable': True,
    'license': 'LGPL-3',
    'maintainers': ['Tardo', 'SplashS'],
    'name': 'Web Responsive',
    'price': 39.0,
    'sequence': 1,
    'summary': 'Responsive web client, community-supported',
    'version': '19.0.1.1.0',
    'website': 'https://github.com/dnaj25/odoo-addons'}