# -*- coding: utf-8 -*-
{   'application': True,   'author': 'dnaj25',
    'category': 'Invoicing Management',
    'company': 'Odoo Mates',
    'currency': 'EUR',
    'data': [   'security/ir.model.access.csv',
                'views/om_daily_reports.xml',
                'wizard/daybook.xml',
                'wizard/cashbook.xml',
                'wizard/bankbook.xml',
                'report/reports.xml',
                'report/report_daybook.xml',
                'report/report_cashbook.xml',
                'report/report_bankbook.xml'],
    'depends': ['account', 'community_pdf_reports'],
    'description': 'Cash Book, Day Book and Bank Book Report For Odoo 19',
    'images': ['static/description/banner.png'],
    'license': 'LGPL-3',
    'live_test_url': 'https://www.youtube.com/watch?v=PEh-an8iCO0',
    'maintainer': 'Odoo Mates',
    'name': 'Daily Financial Books & Reports',
    'price': 19.0,
    'sequence': '10',
    'summary': 'Cash Book, Day Book and Bank Book Report For Odoo 19',
    'support': 'odoomates@gmail.com',
    'version': '1.0.1',
    'website': 'https://github.com/dnaj25/odoo-addons'}